FROM python:3.8
ENV PYTHONUNBUFFERED 1
WORKDIR /django_app
COPY requirements.txt /django_app/requirements.txt
RUN pip install -r requirements.txt
#EXPOSE 8000
#ADD django_app /django_app/
#COPY ../../django_app /django_app/asd


