# Generated by Django 2.2.24 on 2021-08-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('date', models.CharField(max_length=500)),
                ('site', models.CharField(max_length=500)),
            ],
        ),
    ]
