version: "3.8"
services:
  db:
    image: 'mysql:latest'
    container_name: 'project_db'
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ../django_app:/var/lib/mysql/data
  app:
    build: ./app
    container_name: 'project_app'
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../django_app:/django_app
